language: go
go:
  - 1.8.x
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

cache:
  directories:
    - $HOME/gopath/pkg

notifications:
  email: false

install:
  - glide update
  - go get -u gopkg.in/alecthomas/gometalinter.v1 && gometalinter.v1 --install

script:
  - go test -race -cover -covermode=set -coverprofile=coverage.txt && bash <(curl -s https://codecov.io/bash)
  - gometalinter.v1 --config .linter_test.json
  - gometalinter.v1 --config .linter.json
